// AshLog — Insights Engine (Stub/Mock)
// Generates personalized wellness observations from logged data
// Only produces insights backed by sufficient data points

export interface WellnessInsight {
  id: string;
  type: "cycle_sleep" | "wellness" | "pattern";
  title: string;
  description: string;
  icon: string;
  dataPoints: number;
  confidence: number;
}

// Minimum data thresholds before generating insights
const MIN_PERIOD_LOGS = 3;
const MIN_SLEEP_LOGS = 7;
const MIN_MOOD_LOGS = 7;
const MIN_SYMPTOM_LOGS = 5;

interface DataCounts {
  periodLogs: number;
  sleepLogs: number;
  moodLogs: number;
  symptomLogs: number;
  journalEntries: number;
}

// Mock insight templates — in production, these would be generated by analyzing actual data
const CYCLE_SLEEP_INSIGHTS: WellnessInsight[] = [
  {
    id: "cs-1",
    type: "cycle_sleep",
    title: "Luteal Phase Sleep Impact",
    description: "You tend to sleep 18% less deeply during the luteal phase. Consider earlier bedtimes in the days leading up to your period.",
    icon: "🌙",
    dataPoints: 12,
    confidence: 0.78,
  },
  {
    id: "cs-2",
    type: "cycle_sleep",
    title: "Pre-Period Insomnia Pattern",
    description: "Your insomnia symptoms increase approximately two days before menstruation begins.",
    icon: "💤",
    dataPoints: 8,
    confidence: 0.72,
  },
  {
    id: "cs-3",
    type: "cycle_sleep",
    title: "Follicular Phase Energy",
    description: "Your sleep quality scores are highest during the follicular phase, averaging 4.2 out of 5.",
    icon: "✨",
    dataPoints: 15,
    confidence: 0.85,
  },
];

const WELLNESS_INSIGHTS: WellnessInsight[] = [
  {
    id: "w-1",
    type: "wellness",
    title: "Cycle Regularity",
    description: "Your cycles have become more regular over the past 4 months, averaging 28 days.",
    icon: "📊",
    dataPoints: 4,
    confidence: 0.82,
  },
  {
    id: "w-2",
    type: "wellness",
    title: "Sleep Duration Pattern",
    description: "Sleep quality improves when your bedtime occurs before 10:30 PM.",
    icon: "🕐",
    dataPoints: 20,
    confidence: 0.88,
  },
  {
    id: "w-3",
    type: "wellness",
    title: "Energy After Rest",
    description: "You report higher energy levels on days following 8+ hours of sleep.",
    icon: "⚡",
    dataPoints: 14,
    confidence: 0.91,
  },
];

const PATTERN_INSIGHTS: WellnessInsight[] = [
  {
    id: "p-1",
    type: "pattern",
    title: "Headache Pattern",
    description: "Headaches occur most often during ovulation. Consider tracking hydration during this phase.",
    icon: "🔍",
    dataPoints: 6,
    confidence: 0.65,
  },
  {
    id: "p-2",
    type: "pattern",
    title: "Mood Correlation",
    description: "Your mood ratings tend to dip during the late luteal phase but recover quickly once menstruation begins.",
    icon: "💜",
    dataPoints: 10,
    confidence: 0.74,
  },
];

export function generateInsights(dataCounts: DataCounts): WellnessInsight[] {
  const insights: WellnessInsight[] = [];

  // Only surface cycle+sleep insights with sufficient data
  if (dataCounts.periodLogs >= MIN_PERIOD_LOGS && dataCounts.sleepLogs >= MIN_SLEEP_LOGS) {
    insights.push(CYCLE_SLEEP_INSIGHTS[0]);
    if (dataCounts.sleepLogs >= 14) {
      insights.push(CYCLE_SLEEP_INSIGHTS[1]);
    }
  }

  // Wellness insights need multiple data types
  if (dataCounts.periodLogs >= MIN_PERIOD_LOGS) {
    insights.push(WELLNESS_INSIGHTS[0]);
  }
  if (dataCounts.sleepLogs >= MIN_SLEEP_LOGS) {
    insights.push(WELLNESS_INSIGHTS[1]);
    insights.push(WELLNESS_INSIGHTS[2]);
  }

  // Pattern insights need symptom + mood data
  if (dataCounts.symptomLogs >= MIN_SYMPTOM_LOGS) {
    insights.push(PATTERN_INSIGHTS[0]);
  }
  if (dataCounts.moodLogs >= MIN_MOOD_LOGS) {
    insights.push(PATTERN_INSIGHTS[1]);
  }

  return insights;
}

// Default insights shown when insufficient data
export function getOnboardingInsights(): WellnessInsight[] {
  return [
    {
      id: "onboard-1",
      type: "wellness",
      title: "Start Logging to Unlock Insights",
      description: "Log at least 3 periods and 7 sleep entries to start seeing personalized patterns.",
      icon: "🌱",
      dataPoints: 0,
      confidence: 1,
    },
    {
      id: "onboard-2",
      type: "wellness",
      title: "Your Data, Your Patterns",
      description: "The more you log, the smarter AshLog becomes at finding correlations unique to you.",
      icon: "📈",
      dataPoints: 0,
      confidence: 1,
    },
  ];
}

// Ash AI assistant mock responses
export function getAshResponse(question: string, context: any = null): string {
  const q = question.toLowerCase();

  const getDaysSince = (dateString?: string | Date) => {
    if (!dateString) return null;
    return Math.floor((new Date().getTime() - new Date(dateString).getTime()) / (1000 * 60 * 60 * 24));
  };

  const daysSincePeriod = getDaysSince(context?.lastPeriod?.date);
  
  if (q.includes("next period") || q.includes("when is my")) {
    if (daysSincePeriod !== null) {
      const estimatedCycleLength = 28;
      const daysUntilNext = estimatedCycleLength - daysSincePeriod;
      if (daysUntilNext > 0) {
        return `Based on your last logged period (${daysSincePeriod} days ago), your next period is estimated to start in about ${daysUntilNext} days. Keep in mind that slight variations are completely normal.`;
      } else if (daysUntilNext === 0) {
        return `Based on your cycle history, your next period is estimated to start today.`;
      } else {
        return `Your period is currently estimated to be ${Math.abs(daysUntilNext)} days late. Variations are common, but consider taking a test or consulting a healthcare provider if it persists.`;
      }
    }
    return "I don't have enough data about your last period. Please log your period dates so I can estimate your next cycle.";
  }

  if (q.includes("late") || q.includes("why is my cycle")) {
    if (daysSincePeriod !== null && daysSincePeriod > 28) {
      return `Your period is currently ${daysSincePeriod - 28} days later than the standard 28-day cycle. Variations are common and can be influenced by stress, sleep changes, exercise, or diet. If it is more than 2 weeks late, consider consulting your healthcare provider.`;
    }
    return "Cycle variations of up to 7 days are common and can be influenced by stress, sleep changes, exercise, or diet. If your period is more than 2 weeks late, consider consulting your healthcare provider.";
  }

  if (q.includes("symptoms") || q.includes("before my period")) {
    if (context?.lastMood?.symptoms && context.lastMood.symptoms.length > 0) {
      const parsedSymptoms = typeof context.lastMood.symptoms === 'string' 
        ? JSON.parse(context.lastMood.symptoms) 
        : context.lastMood.symptoms;
      if (Array.isArray(parsedSymptoms) && parsedSymptoms.length > 0) {
        return `Based on your recent logs, you recently experienced: ${parsedSymptoms.join(", ")}. It's helpful to track these throughout your cycle.`;
      }
    }
    return "Based on your logs, your most common pre-period symptoms are bloating, mild cramps, and mood changes. These typically appear 2-3 days before menstruation. Keep logging your symptoms for better tracking!";
  }

  if (q.includes("regular") || q.includes("how regular")) {
    return "Your cycles over the past few months have been fairly consistent, averaging around 28 days. A variation of 1-2 days is perfectly normal.";
  }

  if (q.includes("sleep") || q.includes("insomnia")) {
    if (context?.lastSleep?.hours) {
      return `I noticed you logged ${context.lastSleep.hours} hours of sleep recently with a quality rating of ${context.lastSleep.quality}/5. Your sleep quality tends to dip during the late luteal phase. Try maintaining a consistent bedtime routine!`;
    }
    return "Your sleep quality tends to dip during the late luteal phase. Try maintaining a consistent bedtime routine during this phase, and consider limiting screen time before bed.";
  }

  if (q.includes("mood") || q.includes("feeling")) {
    if (context?.lastMood?.mood) {
      return `You recently logged your mood as "${context.lastMood.mood}". Your mood patterns show natural fluctuations throughout your cycle. Many women experience lower mood during the late luteal phase, which typically improves once menstruation begins.`;
    }
    return "Your mood patterns show natural fluctuations throughout your cycle. Many women experience lower mood during the late luteal phase, which typically improves once menstruation begins.";
  }

  return "I can help you understand your cycle patterns, sleep quality, and mood trends. Try asking me about your next period, cycle regularity, sleep patterns, or common symptoms.";
}
